Feat/annoucement card
isd-sgcu/sucu-frontend-2024 pull request #14
Opened 2024-09-14 21:38 UTC by amphikapha

### Type of Change

- [x] New features
- [ ] Bug fixes
- [ ] Breaking changes
- [ ] Refactor
- [ ] Documentation updates
- [ ] Other (please specify):

## Description

Annoucement Card with trimTitle for too long title

## Screenshots or GIFs (if applicable)

Already added to Playground 

![Screenshot 2024-09-15 043135](https://github.com/user-attachments/assets/d9f79742-c90d-4704-ab5c-815a43617d9e)

2024-09-14 22:05 UTC, amphikapha commented
I think each card should be clicked and redirect to its own article page, so i added the 5th prop (linkHref) to the component.

2024-09-15 17:40 UTC, punchanabu requested changes
code ok เลยมีเพิ่มนิดเดียวว

2024-09-15 17:40 UTC, punchanabu commented on src/lib/components/AnnoucementCard/AnnoucementCard.svelte
> +		<img src={imageURL} alt={title} width="276" height="276" class="w-[100%] rounded" />
เพิ่ม fallback ไว้ให้หน่อย
```svelte
<div class="p-3 h-[300px] w-[300px]">
    {#if imageURL}
	<img src={imageURL} alt={title} width="276" height="276" class="w-[100%] rounded"/>
    {:else}
	<div class="w-full h-full bg-gray-300 rounded animate-pulse"></div>
    {/if}

</div>
 ```

2024-09-15 17:46 UTC, punchanabu commented
อ่อแล้วก็ของ Card มันมีของ mobile size ด้วยนะ designer เพิ่งเพิ่มมา [tailwind-responsive](https://tailwindcss.com/docs/responsive-design)
<img width="346" alt="Screenshot 2567-09-16 at 00 44 11" src="https://github.com/user-attachments/assets/55c0ec80-1949-4ba6-9b33-cd7ab14cb6af">

2024-09-19 14:30 UTC, amphikapha commented
Already added fallback leaw naka

![Screenshot 2024-09-19 212605](https://github.com/user-attachments/assets/e6f5ac27-a23d-464b-a672-0e84ef246eb0)


and card size for mobile

![Screenshot 2024-09-19 212747](https://github.com/user-attachments/assets/f09de913-3f8c-4f23-b418-ee8e7d04e768)

2024-09-20 12:08 UTC, punchanabu approved these changes

2024-09-20 12:56 UTC, merged