Feat/modal component
isd-sgcu/sucu-frontend-2024 pull request #7
Opened 2024-09-11 14:26 UTC by Chulinuwu

### Type of Change

- [Modal Component ?? ] New features

## Description

Sleep

## Screenshots or GIFs (if applicable)

![modal](https://github.com/user-attachments/assets/8135102a-9f3c-4a89-bb57-bcf9a0035809)

2024-09-12 06:15 UTC, punchanabu reviewed
กดไว้แค่นี้ก่อนเดี่ยวมารีวิวต่อ

2024-09-12 06:15 UTC, punchanabu commented on src/routes/testModal/+page.svelte
You can test your component in `Playground.svelte` na

2024-09-12 06:15 UTC, punchanabu commented on src/lib/components/Modal.svelte
> +					</svg>
This one you can use [svelte-fa](https://www.npmjs.com/package/svelte-fa) and `font-awesome` library to implement this. Take a look at this component from @macgeargear to see the [implementation](https://github.com/isd-sgcu/sucu-frontend-2024/blob/a89dc6bf714b4201ab9ccd7a416cadeae6f7e239/src/lib/components/TabCapsule.svelte)

2024-09-12 06:15 UTC, punchanabu commented on src/lib/components/Modal.svelte
> +	let x = false;
I think changing this variable names to `isClose` will make more sense

2024-09-12 06:15 UTC, punchanabu commented on src/lib/components/Modal.svelte
> +								</svg>
Can you change this to `svelte-fa` + `font-awesome` too ?

2024-09-12 06:15 UTC, punchanabu commented on src/lib/components/Modal.svelte
> +		<!-- <Button variant="default" size="default" on:click={() => closeModal()}>Close Modal</Button> -->
Please remove this `Button` comment since you have the close button already

2024-09-12 09:30 UTC, macgeargear commented on src/lib/components/Modal.svelte
> +		<!-- <Button variant="default" size="default" on:click={() => closeModal()}>Close Modal</Button> -->
note: If you want to use the default button variant, you don’t need to specify the variant. Simply use `<Button>foo</Button>`.

2024-09-13 04:47 UTC, punchanabu requested changes
- remove local storage implementation
- minor code format

2024-09-13 04:47 UTC, punchanabu commented on src/lib/components/store.js
Please group the `Modal.svelte` and `store.js` into one folder called `/Modal` because there will be others component which have the store state as well and it might be also be named so `store.js`

2024-09-13 04:47 UTC, punchanabu commented on src/lib/components/store.js
I also think we don't have to use local storage for this usecase since we don't need to `persist` the modal open state after page reload and there might be unexpected behavior like modal doesn't come up in the future.

2024-09-13 04:47 UTC, punchanabu commented on src/lib/components/store.js
> +export const modalShow = writable(storedModalShow);
- we can just Instead of reading from localStorage, initialize modalShow to false
```typescript
export const modalShow = writable(false);
```

2024-09-13 04:47 UTC, punchanabu commented on src/lib/components/store.js
> +}
you can just remove this since we're not using local storage

2024-09-13 04:47 UTC, punchanabu commented on src/lib/components/store.js
> +}
remove this too

2024-09-13 04:47 UTC, punchanabu commented on src/lib/components/Modal.svelte
> +	}
- can you create an unsubscribe to hold the store subscription we have to `unsubscribe` to prevent memory leak I think 
```typescript
  let unsubscribe: () => void;

  onMount(() => {
    unsubscribe = modalShow.subscribe((value) => {
      isModalOpen = value;
    });
  });

  onDestroy(() => {
    if (unsubscribe) unsubscribe();
  });

  function closeModal() {
    modalShow.set(false);
  }
  ```

2024-09-13 04:47 UTC, punchanabu commented on src/lib/components/Modal.svelte
> +	let isClose = false;
เปลี่ยนชื่ออันนี้เป็น `isModalOpen` ดีกว่าพอเป็น `isClose` แล้ว logic มันสลับกัน my bad bro

2024-09-13 04:47 UTC, punchanabu commented on src/lib/components/Modal.svelte
> +				<button class="hover:scale-105 transition-all" on:click={() => closeModal()}>
`on:click={closeModal}` ได้นะ

2024-09-13 04:59 UTC, macgeargear commented
When your commit is behind the dev branch, you can update your branch to include the latest changes from dev na krub

2024-09-13 05:06 UTC, punchanabu commented
> When your commit is behind the dev branch, you can update your branch to include the latest changes from dev na krub

This is how you do it na
```
# commit อะไรให้เรียบร้อยก่อน
git checkout dev
git pull
git checkout {your_branch_name}
git merge dev
```

2024-09-13 05:51 UTC, punchanabu approved these changes
Ready to merge

2024-09-13 05:53 UTC, merged